# Generated by Django 3.2 on 2021-06-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended',
        ),
        migrations.AddField(
            model_name='classmember',
            name='attended',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
