# Generated by Django 3.2 on 2021-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210617_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmember',
            name='attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='matric_number',
            field=models.CharField(max_length=11),
        ),
    ]
