# Generated by Django 3.2 on 2021-06-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210617_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name_plural': 'course'},
        ),
    ]
