# Generated by Django 3.2 on 2021-06-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmember',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
